//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lasttry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Агент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Агент()
        {
            this.Заявка = new HashSet<Заявка>();
            this.Предложение = new HashSet<Предложение>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public string Тип { get; set; }
        public string Юридический_адрес { get; set; }
        public Nullable<int> ИНН { get; set; }
        public Nullable<int> КПП { get; set; }
        public string ФИО_директора { get; set; }
        public Nullable<int> Контактные_данные { get; set; }
        public byte[] Логотип { get; set; }
        public Nullable<int> Приоритет { get; set; }
        public Nullable<int> ID_точки_продаж { get; set; }
        public Nullable<int> Рейтинг { get; set; }
        public Nullable<double> Скидка { get; set; }
    
        public virtual Точка_продажи Точка_продажи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Предложение> Предложение { get; set; }
    }
}
