//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lasttry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        public int ID { get; set; }
        public Nullable<int> ID_агента { get; set; }
        public Nullable<int> ID_менеджера { get; set; }
        public Nullable<int> ID_продукции { get; set; }
        public string Тип_доставки { get; set; }
        public Nullable<decimal> Сумма_к_оплате { get; set; }
        public string Статус_проверки { get; set; }
    
        public virtual Агент Агент { get; set; }
        public virtual Менеджер Менеджер { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
